/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.linkgest;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;



/**
 *
 * @author Amine
 */
public class menu extends javax.swing.JDialog {

    Connection con;
    String qui;
    protected String nom;
    protected String prenom;
    protected String adresse;
    protected String tel;



    /**
     * Creates new form menu
     */
    public menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        liste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usertab = new javax.swing.JTable();
        ajtbtn = new javax.swing.JButton();
        supbtn = new javax.swing.JButton();
        rechbtn = new javax.swing.JButton();
        rechfl = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        nomfl = new javax.swing.JTextField();
        prenomfl = new javax.swing.JTextField();
        telfl = new javax.swing.JTextField();
        adrssfl = new javax.swing.JTextField();
        choix = new javax.swing.JComboBox<>();
        pdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IDU", "Nom", "Prénom", "Téléphone", "adresse", "Somme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usertab.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                usertabAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(usertab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 380, 400));

        ajtbtn.setText("Ajoutez");
        ajtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajtbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ajtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 80, -1));

        supbtn.setText("suprimé");
        supbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supbtnActionPerformed(evt);
            }
        });
        getContentPane().add(supbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, -1, -1));

        rechbtn.setText("rechrche");
        rechbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rechbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        rechfl.setText("jTextField1");
        rechfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechflActionPerformed(evt);
            }
        });
        rechfl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rechflKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechflKeyReleased(evt);
            }
        });
        getContentPane().add(rechfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 168, 30));

        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        nomfl.setText("nom");
        nomfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomflActionPerformed(evt);
            }
        });
        getContentPane().add(nomfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 168, -1));

        prenomfl.setText("prenom");
        prenomfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomflActionPerformed(evt);
            }
        });
        getContentPane().add(prenomfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 168, -1));

        telfl.setText("tel");
        telfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telflActionPerformed(evt);
            }
        });
        getContentPane().add(telfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 168, -1));

        adrssfl.setText("adress");
        getContentPane().add(adrssfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 168, -1));

        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilisateurs", "Clients" }));
        choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixActionPerformed(evt);
            }
        });
        getContentPane().add(choix, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, 30));

        pdf.setText("PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });
        getContentPane().add(pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amine\\Music\\digital-ge2ed7fe4f_1280.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -10, 1160, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajtbtnActionPerformed
        String req;
        try {    
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            
            this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/link","root","");
             switch (choix.getSelectedItem().toString()) {
            case "Utilisateurs":
               req="insert into utili(nom,prenom,adress,usertel) values(?,?,?,?)" ;                break;
            case "Clients":
                req="insert into client(nom,prenom,adress,clienttel) values(?,?,?,?)" ;                break;
            default:
              req="insert into utili(nom,prenom,adress,usertel) values(?,?,?,?)" ;
                break;
        }
            PreparedStatement ps= con.prepareStatement(req); 
            ps.setString(1,nomfl.getText().toString());
            ps.setString(2,prenomfl.getText().toString());
            ps.setString(3,adrssfl.getText().toString());
            ps.setString(4,telfl.getText().toString());
            ps.execute();
           JOptionPane jop1 = new JOptionPane();
            jop1.showMessageDialog(null, "l'utilisateur est ajouter", "Ajout", JOptionPane.INFORMATION_MESSAGE);
            liste();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ajtbtnActionPerformed

    private void supbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supbtnActionPerformed
      String req ;
        try {    
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/link","root","");
            
           
           System.out.print(usertab.getModel().getValueAt(usertab.getSelectedRow(),0));
           
            switch (choix.getSelectedItem().toString()) {
            case "Utilisateurs":
               req="DELETE FROM utili WHERE userid=?" ;                break;
            case "Clients":
                req="DELETE FROM client WHERE clientid=?" ;                break;
            default:
              req="DELETE FROM utili WHERE userid=?" ;
                break;
        }
           
            PreparedStatement ps= con.prepareStatement(req);
            ps.setString(1, (String) usertab.getModel().getValueAt(usertab.getSelectedRow(),0));
            ps.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
          

JOptionPane jop1 = new JOptionPane();
            jop1.showMessageDialog(null, "l'utilisateur est suprime", "delete", JOptionPane.INFORMATION_MESSAGE);

        
        
        
        
        
        
        
        
        

        liste();
        // TODO add your handling code here:
    }//GEN-LAST:event_supbtnActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        liste();





        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void nomflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomflActionPerformed

    private void prenomflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomflActionPerformed

    private void telflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telflActionPerformed

    private void usertabAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usertabAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_usertabAncestorRemoved

    private void rechbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechbtnActionPerformed

           try {
            Class.forName("com.mysql.jdbc.Driver");    
            try {
                this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/link","root","");
            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           String req="select * from utili where nom=? ";
        try {
            ResultSet rs;
            PreparedStatement ps= con.prepareStatement(req); 
            ps.setString(1,rechfl.getText() );
            rs=ps.executeQuery();
                   
DefaultTableModel model=(DefaultTableModel) usertab.getModel();
model.setRowCount(0);
while(rs.next()){
    model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(4)});
}
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_rechbtnActionPerformed

    private void rechflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechflActionPerformed

    private void rechflKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechflKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rechflKeyReleased

    private void rechflKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechflKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechflKeyPressed

    private void choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixActionPerformed
        // TODO add your handling code here:
        this.qui=choix.getSelectedItem().toString();
        
        
    }//GEN-LAST:event_choixActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed

String path="";


Document doc = new Document();
    
JFileChooser j = new JFileChooser();
j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
int x = j.showSaveDialog(this);
if (x==JFileChooser.APPROVE_OPTION){
   
    path=j.getSelectedFile().getPath();
    
}
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"info.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(5);
            //header
            tbl.addCell("ID");
            tbl.addCell("nom");
            tbl.addCell("prenom");
            tbl.addCell("tel");
            tbl.addCell("adress");
            
            for (int i = 0; i < usertab.getRowCount(); i++) {
                String id = usertab.getValueAt(i, 0).toString();
                 String nom = usertab.getValueAt(i, 1).toString();
                String prenom = usertab.getValueAt(i, 2).toString();
                String tel = usertab.getValueAt(i, 3).toString();
                String adress= usertab.getValueAt(i, 4).toString();
                   tbl.addCell(id);
                   tbl.addCell(nom);
                   tbl.addCell(prenom);
                   tbl.addCell(tel);
                   tbl.addCell(adress);
                
            }

            
                    doc.add(tbl);
                    doc.close();
            
            
            
            
            
            
            
            
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pdfActionPerformed

   
    
    void liste( ){
        String req;
                try {
            Class.forName("com.mysql.jdbc.Driver");    
            try {
                this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/link","root","");
            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ///////////////////////////////////////////
        switch (choix.getSelectedItem().toString()) {
            case "Utilisateurs":
                req="select * from utili ";
                break;
            case "Clients":
                req="select * from client ";
                break;
            default:
                req="select * from utili" ;
                break;
        }

        try {
            PreparedStatement ps= con.prepareStatement(req); 
            ResultSet rs =ps.executeQuery();
DefaultTableModel model=(DefaultTableModel) usertab.getModel();
model.setRowCount(0);
while(rs.next()){
    model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(4)});
}
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }


        
        
    }
    
    /**
     * 
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatAtomOneDarkIJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menu dialog = new menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrssfl;
    private javax.swing.JButton ajtbtn;
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomfl;
    private javax.swing.JButton pdf;
    private javax.swing.JTextField prenomfl;
    private javax.swing.JButton rechbtn;
    private javax.swing.JTextField rechfl;
    private javax.swing.JButton refresh;
    private javax.swing.JButton supbtn;
    private javax.swing.JTextField telfl;
    private javax.swing.JTable usertab;
    // End of variables declaration//GEN-END:variables
}
